language: android

os: linux

android:
  components:
    - tools
    - build-tools-29.0.2
    - platform-tools
    - android-29

addons:
  sonarcloud:
    organization: "magicphotos-github"
    token:
      secure: "d5aoE8N2kOqULXYBeTkfJhFu4oX6FDb78znhMlzDKAIpF7STZ3ax7QsTu+gr4dfZLkEKXOk0w1glciqeTsks5NvpbwiKcKV64OHwTXQEoaS46UMCpUFAQ696BgGwo7rwRcF642qVkwaxjbvUvxRHFkWvYJGALNwFkxM+oGe7s6KNhY0690m7jfDwqIAAV6DFwWEEO1Ca5iLKuMvheciMXPLN22YJQo7WDPHnUdb5Lb9LqC595LhyppgEyuYBwrzO17ZdICpx4EZMBD1deCRGY5zhsevopuX/12YLhjvP/cTxI+aOeaRAWy/DfBH/Eia2loUooNCqJ4hJqyhLEf9QkpajeQV55nruRIsbT14R7zZcVptVZRV9op+xYwcPrIB9NWMO7BR1pBSrfXn5oP2+CGdtes3CPW1S5aXwLJdJMRITcVhI6YDGPAf7RWjmHvjJ5thG8g1CEeAYbkeyPnQrWzdHP6TOX223dkhjhN3/mxVVB4xB7a7RB+58Q/TpOY5M9E2hOu7pRN+OviQrz3cKZKrpkZLdvCWPfNKzC9avSp6qhgpt+UBiwZ7bV/pwn/XwtI5XaeFmXi/jIQ7TWxzHY9cwANjprS328NZmuysts6cpUwcRLc0nCnf2CfodpCwzweZlJizEIQqQhVQ2E0YPr22Qt6sPdtInJhTNscJhrq0="

install:
  - |
    echo && \
    echo "------ INSTALLATION OF LINUX PACKAGES -----" && \
    echo && \
    sudo apt-get -y install p7zip-full oracle-java8-installer openjdk-11-jdk && \
    echo && \
    echo "------- INSTALLATION OF ANDROID NDK -------" && \
    echo && \
    yes | sdkmanager --verbose "ndk;21.0.6113669" && \
    echo && \
    echo "------- INSTALLATION OF QT PACKAGES -------" && \
    echo && \
    bash tools/install-qt.sh --version 5.12.9 --target android --toolchain android_armv7 --directory "$HOME/Qt" qtbase qtdeclarative qtquickcontrols2 qtpurchasing qtandroidextras && \
    echo && \
    echo "----------- END OF INSTALLATION -----------" && \
    echo

script:
  - |
    echo && \
    echo "---------- ENVIRONMENT VARIABLES ----------" && \
    echo && \
    export JAVA_HOME=/usr/lib/jvm/java-8-oracle && \
    export ANDROID_SDK_ROOT=/usr/local/android-sdk && \
    export ANDROID_NDK_ROOT=/usr/local/android-sdk/ndk/21.0.6113669 && \
    export ANDROID_NDK_HOST=linux-x86_64 && \
    export ANDROID_PLATFORM=android-29 && \
    export PATH="$HOME/Qt/5.12.9/android_armv7/bin:$ANDROID_NDK_ROOT/prebuilt/$ANDROID_NDK_HOST/bin:$PATH" && \
    export QMAKE_CFLAGS_ENV="-Werror" && \
    export QMAKE_CXXFLAGS_ENV="-Werror" && \
    echo && \
    echo "--------- UNSHALLOW GIT FOR SONAR ---------" && \
    echo && \
    git fetch --unshallow && \
    echo && \
    echo "---------- CREATE BUILD DIRECTORY ---------" && \
    echo && \
    mkdir .build && \
    cd .build && \
    echo && \
    echo "------------------ QMAKE ------------------" && \
    echo && \
    qmake ../magicphotos.pro && \
    echo && \
    echo "------------------ MAKE -------------------" && \
    echo && \
    make all && \
    echo && \
    echo "-------------- MAKE INSTALL ---------------" && \
    echo && \
    make install INSTALL_ROOT=android-build && \
    echo && \
    echo "------------- ANDROIDDEPLOYQT -------------" && \
    echo && \
    androiddeployqt --input android-libmagicphotos.so-deployment-settings.json --output android-build --android-platform "$ANDROID_PLATFORM" --deployment bundled --gradle --no-gdbserver && \
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then \
        echo && \
        echo "-------------- SONAR WRAPPER --------------" && \
        echo && \
        build-wrapper-linux-x86-64 --out-dir bw-output make clean all && \
        echo && \
        echo "-------------- SONAR SCANNER --------------" && \
        echo && \
        cd .. && \
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && \
        sonar-scanner -Dsonar.projectKey=magicphotos_magicphotos-android \
                      -Dsonar.projectName="MagicPhotos Android" \
                      -Dsonar.sources=. \
                      -Dsonar.sourceEncoding=UTF-8 \
                      -Dsonar.exclusions="qml/**/*,translations/*" \
                      -Dsonar.cfamily.build-wrapper-output=.build/bw-output \
                      -Dsonar.cfamily.cache.enabled=false \
                      -Dsonar.cfamily.threads=1 \
                      -Dsonar.java.source=1.7 \
                      -Dsonar.java.binaries=.build; \
    fi
